---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_dock: true

dockitems_remove:
  - Launchpad
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Freeform
  - TV
  - Podcasts
  - "App Store"
  - Music
  - Numbers
  - Pages

dockitems_persist: []

dotfiles_repo: https://github.com/sitek94/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore_global
  - .prettierrc
  - maciek.bttpreset

homebrew_installed_packages:
  - git
  - github/gh/gh
  - node
  - nvm
  - ssh-copy-id
  - openssl
  - wget
  - {
      name: zsh-autosuggestions,
      path: "~/.oh-my-zsh/plugins/zsh-autosuggestions",
    }
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - bettertouchtool
  - brave-browser
  - docker
  - firefox
  - google-chrome
  - iterm2
  - karabiner-elements
  - obsidian
  - slack
  - spotify
  - todoist
  - visual-studio-code
  - webstorm

npm_packages:
  - prettier
  - eslint
