configure_dotfiles: false
configure_dock: true

dockitems_remove:
  - Launchpad
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Freeform
  - TV
  - Podcasts
  - 'App Store'
  - Music
  - Numbers
  - Keynote
  - Pages

dockitems_persist: []

homebrew_installed_packages:
  - 1password-cli
  - bat # cat with syntax highlighting
  - blackhole-2ch # Record screen with internal audio: https://github.com/ExistentialAudio/BlackHole
  - bun
  - ffmpeg
  - git
  - pnpm
  - gh
  - jq
  - node
  - nvm
  - openssl
  - qview
  - rust
  - ssh-copy-id
  - unzip
  - wget
  - yt-dlp # Youtube CLI downloader
  - {
      name: zsh-autosuggestions,
      path: '~/.oh-my-zsh/plugins/zsh-autosuggestions',
    }
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - oven-sh/bun

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - arc
  - bettertouchtool
  - brave-browser
  - calibre
  - discord
  - docker
  - firefox
  - font-fira-code
  - google-chrome
  - karabiner-elements
  - logitech-options
  - obs
  - obsidian
  - postman
  - notion
  - setapp
  - slack
  - raycast
  - spotify
  - todoist
  - visual-studio-code
  - warp
  - webstorm
  - vlc
  - zoom

npm_packages:
  - pnpm
  - prettier
  - eslint
  - typescript
  - ts-node
