# macOs Ventura has ZSH already set as default shell, so the commented steps below are not needed.
# - name: Install ZSH
#   community.general.homebrew:
#     name: zsh
# - name: Change shell to zsh
#   shell: chsh -s $(which zsh)

- name: Install Oh My Zsh
  # Note that the --keep-zshrc flag is used to prevent Oh My Zsh from overwriting the existing .zshrc file.
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc

- name: Install zsh-autosuggestions
  community.general.homebrew:
    name: zsh-autosuggestions
